backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
logo_url: https://www.totalstopfireperu.com/img/logo.svg

collections: 
  - name: 'Empresa'
    label: 'Empresa'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/pages/empresa/office-hours.md'
        name: 'office-hours'
        label: 'Horario de oficina'
        description: 'Horario de oficina'
        fields:
          - {label: 'OfficeHours', name: 'widgets', widget: 'hidden', default: 'OfficeHours'}
          - {label: 'Titulo', name: 'titulo', widget: 'string'}
          - {label: 'Lunes', name: 'lunes', widget: 'string'}
          - {label: 'Martes', name: 'martes', widget: 'string'}
          - {label: 'Miércoles', name: 'miercoles', widget: 'string'}
          - {label: 'Jueves', name: 'jueves', widget: 'string'}
          - {label: 'Viernes', name: 'viernes', widget: 'string'}
          - {label: 'Sabado', name: 'sabado', widget: 'string'}
          - {label: 'Domingo', name: 'domingo', widget: 'string'}

      - file: 'src/pages/empresa/contact-info.md'
        name: 'contact-info'
        label: 'Datos de contacto'
        description: 'Datos de contacto'
        fields:
          - {label: 'ContactInfo', name: 'widgets', widget: 'hidden', default: 'ContactInfo'}
          - {label: 'Titulo', name: 'titulo', widget: 'string'}
          - {label: 'Dirección', name: 'direccion', widget: 'string'}
          - {label: 'Coordenadas', name: 'coordenadas', widget: 'string'}
          - {label: 'Teléfono', name: 'telefono', widget: 'string'}
          - {label: 'Móvil', name: 'movil', widget: 'string'}
          - {label: 'Correo electrónico', name: 'correo', widget: 'string'}         

      - file: "src/pages/empresa/social-links.md"
        label: "Redes Sociales"
        name: "social-links"
        description: 'Datos de contacto'
        fields:
          - {label: "SocialLinks", name: "social", widget: "hidden", default: "SocialLinks"}
          - label: "Red Social"
            name: redsocial
            widget: list
            fields:
              - {label: Tipo, name: tipo, widget: select , options: ["Facebook", "Google-Plus", "Youtube","Instagram","Twitter","Skype"]}
              - {label: "Dirreción", name: direccion, widget: string}

      - file: "src/pages/empresa/enterprise-feature.md"
        label: "característica de la empresa"
        name: "enterprise-feature"
        description: 'característica de la empresa'
        fields:
          - {label: "EnterpriseFeature", name: "widgets", widget: "hidden", default: "EnterpriseFeature"}
          - label: 'Característica'
            name: caracteristica
            widget: list
            fields:
              - {label: Titulo, name: titulo, widget: string}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - {label: Imagen, name: imagen, widget: image}

  - name: "slider"
    label: "Portada"
    delete: false
    editor:
      preview: false
    files:
      - file: "src/pages/slider/home.md"
        label: "Inicio"
        name: "slider-home"
        fields:
          - {label: "SliderHome", name: "slider", widget: "hidden", default: "SliderHome"}
          - label: Pagina
            name: pagina
            widget: list
            fields:
              - {label: Titulo, name: titulo, widget: string}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - {label: Imagen, name: imagen, widget: image}

  - name: "servicios"
    label: "Servicios"
    delete: false
    editor:
      preview: false    
    files:
      - file: "src/pages/servicios/recarga_de_extintores/index.md"
        label: "Recarga de Extintores"
        name: "recarga_de_extintores"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-service"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/servicios/mantenimiento/index.md"
        label: "Mantenimiento"
        name: "mantenimiento"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-service"}
          - {label: Title, name: title, widget: string}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/servicios/capacitacion/index.md"
        label: "Capacitación"
        name: "capacitacion"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-service"}
          - {label: Title, name: title, widget: string}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"} 
    
      - file: "src/pages/servicios/inspecciones/index.md"
        label: "Inspecciones"
        name: "inspecciones"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-service"}
          - {label: Title, name: title, widget: string}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Descripción", name: "descripcion", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"} 

  - name: "brand"
    label: "Marcas de extintores"
    folder: "src/pages/brand-products"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brand-products"}
      - {label: "Código", name: "codigo", widget: "string"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: Imagen, name: imagen, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Paginas"
    delete: false
    editor:
      preview: false    
    files:
      - file: "src/pages/paginas/nosotros/index.md"
        label: "Nosotros"
        name: "nosotros"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/paginas/servicios/index.md"
        label: "Servicios"
        name: "servicios"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/paginas/productos/index.md"
        label: "Productos"
        name: "productos"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Portada", name: "portada", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}                         